# Generated by Django 5.2.12 on 2026-03-03 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mint", models.CharField(max_length=64, unique=True)),
                ("symbol", models.CharField(blank=True, max_length=32, null=True)),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField()),
                ("source", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="PairSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair_address", models.CharField(max_length=128)),
                ("dex_id", models.CharField(max_length=64)),
                ("liquidity_usd", models.FloatField(null=True)),
                ("volume_24h", models.FloatField(null=True)),
                ("buys_1h", models.IntegerField(default=0)),
                ("sells_1h", models.IntegerField(default=0)),
                ("price_change_5m", models.FloatField(null=True)),
                ("traders_1h", models.IntegerField(default=0)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scanner.token"
                    ),
                ),
            ],
        ),
    ]
