# Generated by Django 5.2.4 on 2026-03-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="alert_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="token",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="token",
            name="last_scored_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scored_tokens",
                to="scanner.pairsnapshot",
            ),
        ),
    ]
