# Generated by Django 5.2.12 on 2026-03-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_token_alert_sent_token_is_rejected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="safety_flags",
            field=models.JSONField(
                blank=True, help_text="Cached Solsniffer response", null=True
            ),
        ),
    ]
