# Generated by Django 5.2.12 on 2026-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenscore",
            name="ai_analysis",
            field=models.JSONField(
                blank=True,
                help_text="Gemini AI verdict: {confidence, summary}",
                null=True,
            ),
        ),
    ]
